{ lib, ... }:

{
  imports = [
    # Include the results of the hardware scan
    # (modulesPath + "/installer/scan/not-detected.nix")
    ./linux-shared.nix
  ];

  # Bootloader configuration - adjust for your system
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Networking
  networking.hostName = "linux-desktop";

  # Hardware configuration - this would typically be generated by nixos-generate-config
  # You'll need to customize this for your specific hardware

  # Example hardware configuration (uncomment and adjust as needed):
  # boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  # boot.kernelModules = [ "kvm-intel" ];  # or "kvm-amd" for AMD

  # Example filesystem configuration:
  # fileSystems."/" = {
  #   device = "/dev/disk/by-uuid/your-root-uuid";
  #   fsType = "ext4";
  # };
  #
  # fileSystems."/boot" = {
  #   device = "/dev/disk/by-uuid/your-boot-uuid";
  #   fsType = "vfat";
  # };

  # Enable GNOME desktop environment
  services.xserver.desktopManager.gnome.enable = true;

  # Optional: Enable additional desktop environments
  # services.xserver.desktopManager.plasma5.enable = true;
  # services.xserver.windowManager.i3.enable = true;

  # Graphics drivers - uncomment as needed
  # services.xserver.videoDrivers = [ "nvidia" ];  # For NVIDIA
  # services.xserver.videoDrivers = [ "amdgpu" ];  # For AMD
  # hardware.opengl.enable = true;

  # Enable podman with some example containers
  services.podman.enable = true;
  services.podman.containers = {
    # Example container - remove or modify as needed
    # hello-world = {
    #   image = "docker.io/library/hello-world";
    #   autoStart = false;
    # };
  };

  # Additional hardware support
  hardware.bluetooth.enable = true;
  hardware.pulseaudio.enable = false; # We use PipeWire instead

  # Enable touchpad support for laptops
  services.xserver.libinput.enable = true;

  # Power management for laptops
  services.tlp.enable = lib.mkDefault true;

  # Additional services
  services.openssh.enable = true;
  services.flatpak.enable = true;

  # Firewall
  networking.firewall.enable = true;
  # networking.firewall.allowedTCPPorts = [ ... ];
  # networking.firewall.allowedUDPPorts = [ ... ];
}
